window_ratio_width: 16
window_ratio_height: 9


default:
  mouse_sensi: 1.0  # deg/mm
  
  window:
    resolution:
      width: 1920
      height: 1080
    monitor:
      width: 0.5313
      height: 0.2988
    fov:
      width: 103
      height: 70.533

  range:
    target:
      pos:
        azim:
          max: 37.0
          min: 2.0
        elev:
          max: 21.0
          min: 1.0
      radius:
        max: 0.013
        min: 0.001
        bd_sample:  # Boundary sample
          max: 0.0
          min: 0.0
      aspeed:   # Angular speed in orbit
        max: 40.0
        min: 0.0
        bd_sample:
          max: 0.0
          min: 0.05
    camera:
      max_dev_rad: 0.0045 

