default:
  callback:
    save_freq: 2000000
    eval_freq: 50000
    eval_ep: 2048
  
  model:
    mlp:
      arch: [512, 512, 512]
      concat: [0, 1, 2, 3]
      embed:
    batch: 2048
    lr: 0.00005
    gamma: 0.9
    entropy: auto
    target_entropy: auto
  
  train:
    step: 20000000
    log_freq: 100
